name: Alerta

on:
  push:
    branches: [main]

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ejecutar hola mundo
        run: node index.js

      - name: Enviar notificación a ntfy
        env:
          REPO: ${{ github.repository }}
          AUTOR: ${{ github.actor }}
        run: |
          SALIDA=$(node index.js)
          MENSAJE=$(printf ' **¡Ejecución Exitosa!**\n\n```\n%s\n```\n\n%s hizo push a main en %s' "$SALIDA" "$AUTOR" "$REPO")
          curl -H "Title: GitHub Actions - ITLA" \
               -H "Tags: github,ci" \
               -H "Markdown: yes" \
               -d "$MENSAJE" \
               https://ntfy.sh/devops-itla